"""initial migration

Revision ID: 3c7e6046cf6
Revises: None
Create Date: 2014-06-02 07:37:50.189763

"""

# revision identifiers, used by Alembic.
revision = '3c7e6046cf6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=64), nullable=True),
    sa.Column('last', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('street_addr1', sa.String(length=64), nullable=True),
    sa.Column('street_addr2', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=9), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F'), nullable=True),
    sa.Column('home_box', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competitions')
    op.drop_index('ix_users_username', 'users')
    op.drop_table('users')
    ### end Alembic commands ###
